### ISSUE TITLE
Angular 13 Support

### ISSUE THREAD

**Issue by austinkurtti** [w11k/angular-sticky-things#110]
Attempting to install the latest version (1.4.0) of the sticky things package gives the following error with Angular 13:

`npm ERR! peer @angular/common@"^4.0.0 || ^7.0.0 || ^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0 || ^12.0.0" from @w11k/angular-sticky-things@1.4.0`

**Comment by srikanthonl** [comment]
Any ETA for this please?

**Comment by kaihenzler** [comment]
should be fixed in the latest version `1.5.0`

**Comment by srikanthonl** [comment]
@kaihenzler thanks for the v13 support. However, now I get this error when running npm install with 1.5.0:

npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"^6.0.0" from @w11k/angular-sticky-things@1.5.0
npm ERR! node_modules/@w11k/angular-sticky-things
npm ERR!   @w11k/angular-sticky-things@"^1.5.0" from the root project

Looks like RxJS v7 is not supported by this package. We work in a monorepo where all other projects rely on RxJS v7.x. So, can't downgrade it to 6.x :(

**Comment by kaihenzler** [comment]
@srikanthonl should be fixed with `1.5.1`
