### ISSUE TITLE
Template parse error

### ISSUE THREAD

**Issue by chrisj74** [w11k/angular-sticky-things#13]
Hi,

Have added package via npm, included in app.module.ts and used the snippet from the example code.

I get the following error

`Error: Template parse errors:
Can't bind to 'spacer' since it isn't a known property of 'div'. ("rHtml]="category.categoryName" class="flex-grow"></h2>

      <div #spacer></div>

<div stickyThing [ERROR ->][spacer]="spacer">STUCK</div>
`
Using   "@angular/core": "^6.1.9".

I have tried directly importing the directive, but still no luck.

Any help much appreciated.

Cheers

**Comment by CanKattwinkel** [comment]
Have you added the `stickyThing` directive? Since the spacer is an Input. 

**Working example:**
https://stackblitz.com/edit/angular-z3itfx?file=src%2Fapp%2Fapp.component.html

**Comment by CanKattwinkel** [comment]
I'll close this, please re-open if you still see this error.

**Comment by scubafly** [comment]
Got the same issue. I see the working example but somehow that does not work in my app. Must be something wrong with the versions I use or so. I'm getting the exact same error.
Using angular core 7.2.16

I don't see the directive being added in the working example?
