### ISSUE TITLE
MarginTop not being calcuted properly until browser resized

### ISSUE THREAD

**Issue by jaetea** [w11k/angular-sticky-things#16]
I'm running this in an angular app. The one component I have made sticky with a marginTop of 72 doesn't stick until its past the top of the browser window, then will jump to where it should be.

If I resize my browser window it will work properly.

Intial page load (red is sticky element)
![image](https://user-images.githubusercontent.com/3731879/49955120-14c66880-fed0-11e8-98d8-ea043efebfed.png)

Element has scrolled off top of screen

![image](https://user-images.githubusercontent.com/3731879/49955168-2f98dd00-fed0-11e8-8b77-9f202c85a3b5.png)

Element then jumps to where it should be
![image](https://user-images.githubusercontent.com/3731879/49955338-90c0b080-fed0-11e8-89ce-ee972395a30b.png)

Resize browser (horizontal/vertically)

Offset and stickyness is properly calculated
![image](https://user-images.githubusercontent.com/3731879/49955302-7e467700-fed0-11e8-8f6c-ab779c211d8f.png)

**Comment by CanKattwinkel** [comment]
@robertsmith2 @jaetea should be fixed in version 1.1.0!

For any more corner cases there is now a recalculate method exposed.

Thanks for the bug report!
