### ISSUE TITLE
Opening dialog window with overlay causes sticky header to disappear

### ISSUE THREAD

**Issue by jaetea** [w11k/angular-sticky-things#17]
We leverage Angular Material. When you open a dialog window the "is-sticky" class gets removed from the sticky component and the spacer size it set to zero.

Once you close the dialog it reappears.

![image](https://user-images.githubusercontent.com/3731879/50693030-ca826400-1003-11e9-95f2-23bb3db19b53.png)

![image](https://user-images.githubusercontent.com/3731879/50693048-d706bc80-1003-11e9-9a6d-7ecc9728fb36.png)

**Comment by CanKattwinkel** [comment]
Thank you for reporting the issue! 

I'll try to look at it by the end of next week. If you want to speed up things, you can provide a fork of this repository with a mat dialog in the demo page.

**Comment by jaetea** [comment]
This seems to be an issue with the way material handles scrolllock, not with sticky things. Closing
