### ISSUE TITLE
Multiple Sticky Tabs Support

### ISSUE THREAD

**Issue by miked1090** [w11k/angular-sticky-things#2]
It looks like it's pretty close to supporting multiple sticky tabs already, the only issue I notice is when it gets to another sticky tab, the first one will overtake the second one until the second header is scrolled past.

Here is an example of the issue.
https://stackblitz.com/edit/github-vtekep

**Comment by CanKattwinkel** [comment]
Thanks for the effort! 

Multiple use should be possible, you are right. The question is, what would be the best behaviour? 

Either **a)** Header 1 is "sliding" under Header 2 or **b)** stop points are implemented as seen here:
http://somewebmedia.com/hc-sticky/demo_3.html

**Comment by miked1090** [comment]
Anytime :)

I personally like option b better, but they both seem like valid ways to handle it.

**Comment by CanKattwinkel** [comment]
The first version with "boundaries" was implemented in version `0.2.0`. The feature is still in beta and probably needs some more work but the API should be stable:

https://github.com/w11k/angular-sticky-things#boundary-elements
