### ISSUE TITLE
sticky elements flash on safari

### ISSUE THREAD

**Issue by kamechb** [w11k/angular-sticky-things#22]
![stickyflash](https://user-images.githubusercontent.com/208991/51521017-454eda00-1e60-11e9-84d7-c08fc57cf051.gif)

**Comment by norbertnagy** [comment]
Hi, I have the same issue. Is there any resolution for it ?

**Comment by tobiasatw11k** [comment]
@kamechb @norbertnagy issue is fixed in 1.1.9.
![no flash](https://user-images.githubusercontent.com/46442126/67534242-8153eb80-f6cd-11e9-8e7e-38d5841817b6.gif)
