### ISSUE TITLE
The sticky library doesn't work

### ISSUE THREAD

**Issue by Denis-Evseev** [w11k/angular-sticky-things#24]
Thank you for the library

I have tried to install it to my Angular 7 App but it doesn't work anywhere. 
The installation was done in line with documentation:
1) installed the package
2) added the installed module to app.module.ts + imports
3) inserted on the top of my app:
```
<div #spacer></div>
<div stickyThing" [spacer]="spacer">
  I am sticky!
</div>
```

But doesn't work.. Tried app.component, with boundary - still doesn't work
Please help
Cheers

**Comment by matthiasfritsch** [comment]
Same here. Not working on Angular 7...

**Comment by CanKattwinkel** [comment]
Hi @matthiasfritsch and @Denis-Evseev, 

could you please check if there are any runtime errors? I just created an example with Angular 7 and it works for me. I'm confident, we'll fix this issue shortly. 

https://stackblitz.com/edit/angular-5pkty4?file=src%2Fapp%2Fapp.component.html

**Comment by matthiasfritsch** [comment]
Thank you for the reply!
Your sticky works for me now, but my case the problem was a `overflow:auto` inside a `<div>` above. 
Now I will wait for the MarginTop-Fix (https://github.com/w11k/angular-sticky-things/issues/23) :) 
Thank you for the awesome work!

**Comment by CanKattwinkel** [comment]
Already on #23

Sorry, currently I have exams and therefore limited time. Expect the fix to be merged (plus covered with tests by this or next week)
