### ISSUE TITLE
Cannot find name 'DOMRect'

### ISSUE THREAD

**Issue by kaito3desuyo** [w11k/angular-sticky-things#34]
Hello.

I use angular-sticky-things@1.1.2 with Angular 5.2.8. However, I get the following error.

ERROR in node_modules/@w11k/angular-sticky-things/lib/sticky-thing.directive.d.ts(40,53): error TS2304: Cannot find name 'DOMRect'.

Is there a solution?

**Comment by brdzamasina** [comment]
I have exactly the same issue..

**Comment by comemanu** [comment]
same

**Comment by tobiasatw11k** [comment]
@brdzamasina @kaito3desuyo @comemanu please try using the current latest version 1.1.8. if the error still occurs, please provide more information. which angular, typescript version are you using? what does your tsconfig.json look like?
