### ISSUE TITLE
Cannot read property 'addEventListener' of null.

### ISSUE THREAD

**Issue by aspramsh** [w11k/angular-sticky-things#35]
When I add this 
`stickyThing="" [scrollContainer]="'.scroll-container'" `
I get the following error:

> ERROR TypeError: Cannot read property 'addEventListener' of null. 

Could someone help please?
After adding this to .ts file 

`@HostBinding('class') class = 'scroll-container'`
I get this error:

> ERROR DOMException: Failed to execute 'querySelector' on 'Document': ''.scroll-container'' is not a valid selector.
>     at StickyThingDirective.getScrollTarget

**Comment by tobiasatw11k** [comment]
@aspramsh does this error still exist?
