### ISSUE TITLE
Add ghost/placeholder take up space

### ISSUE THREAD

**Issue by mailiam** [w11k/angular-sticky-things#36]
sticky element would collapse stacking when fixed.

to prevent layout bug, fixed element should create placeholder to take up space where it has been before.

current workaround is to wrap `stickyThing` with a div with fixed size.

**Comment by JaxonWright** [comment]
I kind of assumed this already did this. This is a must-have in order to make content not jolt upwards when transitioning the element to be sticky.

**Comment by tobiasatw11k** [comment]
@mailiam @JaxonWright if you could provide an example of desired behavior and a counterexample i'll see what I can do to fix the problem.
