### ISSUE TITLE
[scrollContainer]="'.scroll-container'"  is not working

### ISSUE THREAD

**Issue by Krish-Kannaa** [w11k/angular-sticky-things#39]
**HTML FILE**
<div class="scroll-container" >
  <div #spacer></div>
  <div [spacer]="spacer" stickyThing="" [scrollContainer]="'.scroll-container'" >
    Scroll by!
  </div>
</div>

![image](https://user-images.githubusercontent.com/8122736/59327818-5497cc80-8d08-11e9-98f1-f9bd38d5e51d.png)

**CSS FILE**

.scroll-container
{
  background-color:aquamarine;
  height:1000px;
}

this is my code.

**Comment by Enngage** [comment]
Hey, I seem to be having this issue too. I know for a fact it worked some time before, but doesn't with the latest version.

**Comment by tobiasatw11k** [comment]
@Krish-Kannaa @Enngage please check with version 1.2.1 - possible duplicate of #53
