### ISSUE TITLE
Angular 8 Ivy Support

### ISSUE THREAD

**Issue by michaelkrone** [w11k/angular-sticky-things#41]
Compiling an application with angular-sticky-things as dependency fails with the following errors:

```WARNING in Entry point '@w11k/angular-sticky-things' contains deep imports into '//Development/projekt/node_modules/rxjs/internal/scheduler/animationFrame'. This is probably not a problem, but may cause the compilation of entry points to be out of order.```

```ERROR in Cannot combine @Input decorators with query decorators```

This happens if in tsconfig.json the ivy compiler is enabled:
```json
"angularCompilerOptions": {
    "enableIvy": true
},
```

**Comment by tobiasatw11k** [comment]
hello @michaelkrone, I set up a new project with ivy enabled but couldn't reproduce the issue. can you please try again with the current latest version and check if the error still exists.
