### ISSUE TITLE
Sticky element unstick in wrong scroll position

### ISSUE THREAD

**Issue by kievsash** [w11k/angular-sticky-things#55]
Hi!
Updated my angular to 8.3 and angular-sticky-thing to 1.2.1

Now marginTop works in a weird way: it catches sticky header good on scroll down. But then if I scroll up - my sticky element disappear only if scroll till parent top (scrollTop ==0) but not at position when it became sticky on scroll down (see gif)
![sticky_issue](https://user-images.githubusercontent.com/15340874/67879095-0cf1d000-fb45-11e9-9205-12e41eff41e0.gif)

Pay attention when i scroll up - header disappears too late - when I have scrolled on top

**Comment by kanidjar** [comment]
Hi, same issue here.

![sticky-issue](https://user-images.githubusercontent.com/12607242/68119776-e09ed080-ff03-11e9-9082-2e4b2561841f.gif)

**Comment by tobiasatw11k** [comment]
hello @kievsash @kanidjar thanks for using our library. fixed the issue in v.1.2.2. please take a look, and let me be informed if the issue still exists.

**Comment by kanidjar** [comment]
confirmed, issue fixed :)

thanks @tobiasatw11k

**Comment by kievsash** [comment]
Unfortunately I still observe it
Difference only that now I should not scoll to top to make sticky element disappear but still it dissappears incorrectly
