### ISSUE TITLE
 Error: Can't resolve 'codelyzer/util/isNotNullOrUndefined' 

### ISSUE THREAD

**Issue by MustafaElKhalifa** [w11k/angular-sticky-things#59]
ERROR in ./node_modules/@w11k/angular-sticky-things/fesm5/w11k-angular-sticky-things.js
Module not found: Error: Can't resolve 'codelyzer/util/isNotNullOrUndefined' in 'E:\xampp\htdocs\webzz\dommania\shop.panel\node_modules\@w11k\angular-sticky-things\fesm5'
i ｢wdm｣: Failed to compile.

**Comment by AndrewN93** [comment]
Hello! I have the same issue(
 Can't resolve 'codelyzer/util/isNotNullOrUndefined'

**Comment by DrineTN** [comment]
I'm also dealing the same problem 

ERROR in ./node_modules/@w11k/angular-sticky-things/fesm5/w11k-angular-sticky-things.js
Module not found: Error: Can't resolve 'codelyzer/util/isNotNullOrUndefined'

**Comment by paulhewitt** [comment]
isNullOrUndefined is deprecated (https://nodejs.org/api/util.html#util_util_isnullorundefined_object). I am going to look into it and see if there is a quick, easy fix

**Comment by paulhewitt** [comment]
Remove `import { isNotNullOrUndefined } from 'codelyzer/util/isNotNullOrUndefined';` from w11k-angular-sticky-things.js.

Change lines 345 and 347, removing the use of isNotNullOrUndefined:

`var reachedLowerEdge = isNotNullOrUndefined(this.boundaryElement) ? this.boundaryElement && window.pageYOffset + stickyElementHeight + marginBottom >= (originalVals.bottomBoundary - marginTop * 1.0) : undefined;` 

should be changed to 

`var reachedLowerEdge = (this.boundaryElement==null) ? this.boundaryElement && window.pageYOffset + stickyElementHeight + marginBottom >= (originalVals.bottomBoundary - marginTop * 1.0) : undefined;`

Make the same change to the line with `reachedUpperEdge`

**Comment by tobiasatw11k** [comment]
Hello @MustafaElKhalifa, @AndrewN93, @DrineTN, @paulhewitt,

the problem seemed to be that ng-packagr wasn't able to guess the correct identifier for codelyzer/util/isNotNullOrUndefined when writing the UMD bundle. Providing the module identifier by using umdModuleIds in the library's package file should have solved the issue. Please check within v1.2.4.

@see [here](https://github.com/ng-packagr/ng-packagr/blob/master/docs/dependencies.md#resolving-umd-module-identifiers) for further information

Kind regards,

@tobiasatw11k

**Comment by nutphi** [comment]
Hello, you still need to remove 
import { isNotNullOrUndefined } from 'codelyzer/util/isNotNullOrUndefined';
at line 7 on w11k-angular-sticky-things.js

**Comment by jorgecasariego** [comment]
I'm still having this error.

**Comment by jziggas** [comment]
@tobiasatw11k Yeah this is still happening with 1.2.4

**Comment by DraganMileski** [comment]
+1

**Comment by mikerudd** [comment]
Hi @tobiasatw11k, I've just tried to install 1.2.4 and also got this error: 

```
ERROR in ./node_modules/@w11k/angular-sticky-things/fesm5/w11k-angular-sticky-things.js
Module not found: Error: Can't resolve 'codelyzer/util/isNotNullOrUndefined'
```

**Comment by kalani96746** [comment]
@tobiasatw11k ,  Can this be reopened.  It is still occurring in latest 1.2.4.  @paulhewitt 's fix works.

**Comment by tobiasatw11k** [comment]
Hello @kalani96746 and others, sorry for the delayed response. Lost it on the radar during Christmas days. Issue is now reopened. If @paulhewitt makes a pull request, I'd be very happy to merge it and release a new version.

**Comment by paulhewitt** [comment]
@tobiasatw11k I have been quite busy lately, but I will make a pull request as soon as I can! Hopefully it helps everybody out :)

**Comment by kalani96746** [comment]
@tobiasatw11k 
@paulhewitt 
PR: https://github.com/w11k/angular-sticky-things/pull/65
