### ISSUE TITLE
SSR - Angular Universal - window is not defined

### ISSUE THREAD

**Issue by adrienlamotte** [w11k/angular-sticky-things#62]
Hello ! 

I have an error when using your module with SSR : 

```
ReferenceError: window is not defined at StickyThingDirective.getScrollTarget
```

Any way to fix this ?

Thank you !

**Comment by tobiasatw11k** [comment]
Hello @adrienlamotte,

yes, you can fix it by checking the platform (server, browser) within your template. 

> In HTML
> ```
> <ng-container *ngIf="isBrowser">
>    
>    <div class="header" stickyThing="" [boundary]="boundary" [spacer]="spacer">
> </ng-container>
> ```
> 
> In TS
> 
> ```
> isBrowser;
> constructor(@Inject(PLATFORM_ID) private platformId) { 
>    this.isBrowser = isPlatformBrowser(platformId);
> }

THX @leo6104
@see [here](https://github.com/angular/universal/issues/830)

Kind regards,

@tobiasatw11k

**Comment by adrienlamotte** [comment]
@tobiasatw11k thank you for your answer, but this is not really a solution. 

SSR is mostly used for SEO, so with your workaround the content of my stickyThing (wich is a sidebar menu) will not be rendered by the server... 

Thank you for youyr help :)

**Comment by tobiasatw11k** [comment]
@adrienlamotte maybe this will work for you then:

```html
<ng-container *ngIf="isBrowser; else seo_menu">
   <!-- sidebar with stickyThing directive for browsers (user)-->
   <sidebar-menu stickyThing=""></sidebar-menu>
</ng-container>
<ng-template #seo_menu>
    <!-- sidebar without stickyThing directive for servers (crawlers) -->
    <sidebar-menu></sidebar-menu>
</ng-tempalte>
```

**Comment by adrienlamotte** [comment]
Yes, that would work thank you.

But for further updates of you great module, you should try to handle that inside the directive directly :)

Thanks !
