### ISSUE TITLE
Internet Explorer 11 support

### ISSUE THREAD

**Issue by FabienCH** [w11k/angular-sticky-things#64]
Hello,

I am trying to use sticky-things with internet explorer 11 but I can't make it work (It works on other web browser). I've tried your demo site that does work so I'm thinking maybe in need some polyfills.

Here is the code (It was displayed as flexbox but I removed it just to make sure it does not interfer):
````html
<div #spacer></div>
<div stickyThing [spacer]="spacer" marginTop="10" class="asset-classes-header">
  content
</div>
`````
And here is the rendered HTML: 
![image](https://user-images.githubusercontent.com/17828760/74017119-eb01b800-4993-11ea-8920-609cca3ed10d.png)

I saw in your demo site that the div takes inline style `left: auto; top: auto; width: auto;` but not for me.

EDIT : I have added these polyfills in my pollyfills.ts but it still doesn't work.
````javascript
/** IE9, IE10 and IE11 requires all of the following polyfills. */
import 'core-js/features/array';
import 'core-js/features/object';
import 'core-js/features/symbol';
import 'core-js/features/function';
import 'core-js/features/parse-int';
import 'core-js/features/parse-float';
import 'core-js/features/number';
import 'core-js/features/math';
import 'core-js/features/string';
import 'core-js/features/date';
import 'core-js/features/regexp';
import 'core-js/features/map';
import 'core-js/features/weak-map';
import 'core-js/features/set';

/** IE10 and IE11 requires the following for the Reflect API. */
import 'core-js/features/reflect';
````

Thanks for your help

**Comment by Aterr** [comment]
Same here :(

**Comment by Xpressik** [comment]
Did you find any solution? Cause I am facing the same issue.  SCRIPT1002 on 
![image](https://user-images.githubusercontent.com/19557028/99502589-9016db80-297d-11eb-8a7b-02f36d241a63.png)
