### ISSUE TITLE
Angular 9, ivy compiler and deep imports warning

### ISSUE THREAD

**Issue by ahadjithoma** [w11k/angular-sticky-things#69]
When i am running `ng build` i get this warning

> Warning: Entry point '@w11k/angular-sticky-things' contains deep imports into 'C:/Synectics/SG_DynamicTemplate/Web/sg-web-spa/node_modules/rxjs/internal/scheduler/animationFrame'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

Angular: 9.1.1
sticky-things: 1.2.5
ivy compiler: enabled (default in angular 9)

**Comment by museroom** [comment]
I fixed by: checkout their development branch, then npm run build:lib, then local install with npm install ../angular-sticky-thinks/dist/@w11k/angular-sticky-things

**Comment by andreash92** [comment]
@museroom  thanks for the feedback. I will give it a try although i don't want to have it locally

**Comment by jordankkk** [comment]
any status? this can cause bundle size due to rxjs tree shaking :)

**Comment by sengmann** [comment]
Please try version 1.3.0. It should fix the dependency warning and make sticky things play nice with Angular 10. If you encounter problems feel free to open another issue
