### ISSUE TITLE
feature request: angular 10 support

### ISSUE THREAD

**Issue by wimdetroyer** [w11k/angular-sticky-things#73]
upgrading from angular 9 -> 10 fails on angular-sticky-things with following error message:

![image](https://user-images.githubusercontent.com/58472100/86565103-8dd05980-bf67-11ea-88da-511d4b0d7ca9.png)

**Comment by npoggenburg** [comment]
I support this request. Just learning angular, and its quite hard to do your things i am used to do on angular 10 :D

**Comment by sengmann** [comment]
Please try version 1.3.0. It should fix the dependency warning and make sticky things play nice with Angular 10
