### ISSUE TITLE
After installation project does not compile / errors

### ISSUE THREAD

**Issue by felixunivers** [w11k/angular-sticky-things#78]
After installing sticky-things with Angular 8 project, I get these error on project compilation:

ERROR in ../../node_modules/@w11k/angular-sticky-things/lib/sticky-thing.directive.d.ts:26:9 - error TS1086: An accessor cannot be declared in an ambient context.

26     set marginTop(value: number);
           ~~~~~~~~~
../../node_modules/@w11k/angular-sticky-things/lib/sticky-thing.directive.d.ts:27:9 - error TS1086: An accessor cannot be declared in an ambient context.

27     set marginBottom(value: number);
           ~~~~~~~~~~~~
../../node_modules/@w11k/angular-sticky-things/lib/sticky-thing.directive.d.ts:28:9 - error TS1086: An accessor cannot be declared in an ambient context.

28     set enable(value: boolean);
           ~~~~~~
../twi-lib-a01/src/lib/common/services/messaging/allerts.service.ts:96:9 - error TS2559: Type 'number' has no properties in common with type 'DataDisplayFormatingI'.

96         Date.now()
           ~~~~~~~~~~

**Comment by anjum121** [comment]
If you set up   ` "skipLibCheck": true,` inside your tsconfig.json this issue will be solved 

``` json
{
  "compileOnSave": false,
  "compilerOptions": {
        "skipLibCheck": true,
     }
}
```
